service:
  name: cloudwatch-loggly-lambda-integration

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'eu-west-1'}
  runtime: nodejs12.x
  memorySize: 256
  timeout: 10
  versionFunctions: false

custom:
  browserify:
    fullPaths: true
    exclude:
      - aws-sdk

functions:
  sendToLoggly:
    handler: dist/handlers/sendToLoggly.lambda
    browserify:
      entries:
        - dist/handlers/sendToLoggly.js

resources:
  Outputs:
    SendToLogglyArn:
      Value:
        'Fn::GetAtt': [ SendToLogglyLambdaFunction, Arn ]

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-browserifier

package:
  individually: true
